Improving documentation of `models.encodings.entangling_layer`
qiboteam/qibo pull request #1273
Opened 2024-03-18 16:06 UTC by renatomello

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

2024-03-19 04:20 UTC, renatomello commented on doc/source/api-reference/qibo.rst
> +For instance, we show below an example for each architecture and ``nqubits = 6``.
```suggestion
For instance, we show below an example of each architecture for ``nqubits = 6``.
```

2024-03-19 07:40 UTC, Simone-Bordoni approved these changes

2024-03-19 09:28 UTC, MatteoRobbiati requested changes
Thanks @renatomello!

I think it would be better to standardize a bit more the images in the section. To do this, we should keep the width in the usual range of `400px-800px`, and regulate the height. To do so, I opened #1278, where the `scale` tag is removed and the images widths and heights are rescaled to fit the aforementioned range.

A couple of suggestions follow.

2024-03-19 09:28 UTC, MatteoRobbiati commented on doc/source/api-reference/qibo.rst
> +There are four possible choices of layer ``architechture``:
```suggestion
There are four possible choices of layer ``architecture``:
```

2024-03-19 09:28 UTC, MatteoRobbiati commented on doc/source/api-reference/qibo.rst
> +can be set to any of the two-qubit gates implemented in ``qibo``.
```suggestion
any of the two-qubit gates implemented in ``qibo`` can be selected to customize the entangling layer.
```

2024-03-22 15:33 UTC, MatteoRobbiati approved these changes
Thanks.

2024-03-22 15:33 UTC, merged