Add callback to sgd optimizer
qiboteam/qibo pull request #1335
Opened 2024-05-27 09:03 UTC by MatteoRobbiati

Enabling the callback usage also with SGD optimizers.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2024-06-03 05:42 UTC, andrea-pasquale requested changes
Thanks @MatteoRobbiati, I suggest one small change in tests.

2024-06-03 05:42 UTC, andrea-pasquale commented on tests/test_models_variational.py
> +        pass
Perhaps here it is better to add something to check if the callback is working properly

2024-06-04 12:58 UTC, Edoardo-Pedicillo approved these changes

2024-06-05 13:43 UTC, andrea-pasquale approved these changes

2024-06-05 13:43 UTC, merged