added third order gci
qiboteam/qibo pull request #1342
Opened 2024-06-04 11:46 UTC by wrightjandrew

Added the third order GCI formula to the double blacket flow class

![image](https://github.com/qiboteam/qibo/assets/115216427/69d9bf79-3af9-4813-9026-e2e73f771386)

2024-06-04 13:11 UTC, marekgluza requested changes
Hi @wrightjandrew great, thanks so much! Can you please brush over the suggested doc string?

Please copy paste the final one into the PR main message around your plot.

2024-06-04 13:11 UTC, marekgluza commented on src/qibo/models/dbi/double_bracket.py
>      # TODO: add double commutator (does it converge?)
```suggestion
    """This implements the approximation 
  @wrightjandrew  --- please fill in ---- $$\approx e^{s^2[A,B]+O(s^4)$$
    which is equation (8) in [https://arxiv.org/abs/2111.12177].
    More specifically `step` is taken as $\sqrt{t}$ of the desired duration so we will be approximating as above $e^{sW}$."""
```

2024-06-07 08:30 UTC, marekgluza commented on src/qibo/models/dbi/double_bracket.py
> +    """Implements: $e^{\frac{\\sqrt{5}-1}{2}sH}e^{\frac{\\sqrt{5}-1}{2}sD}e^{-sH}e^{sD}e^{\frac{3-\\sqrt{5}}{2}sH}e^{sD}
```suggestion
    """Implements: $e^{\frac{\\sqrt{5}-1}{2}isH}e^{\frac{\\sqrt{5}-1}{2}isD}e^{-sH}e^{isD}e^{\frac{3-\\sqrt{5}}{2}isH}e^{isD}
```

2024-06-07 09:03 UTC, wrightjandrew commented on src/qibo/models/dbi/double_bracket.py
> +    \approx e^{s^2[H,D]} + O(s^4)$
I think just a minus sign

2024-06-07 09:06 UTC, Edoardo-Pedicillo approved these changes

2024-06-07 13:25 UTC, andrea-pasquale approved these changes
Thanks @wrightjandrew, just a small correction :)

2024-06-10 00:38 UTC, marekgluza approved these changes

2024-06-10 00:40 UTC, marekgluza commented
@andrea-pasquale @Edoardo-Pedicillo can you merge?

2024-06-10 06:17 UTC, merged