Move some notebooks to `tutorials` repository
qiboteam/qibo pull request #1349
Opened 2024-06-06 12:42 UTC by MatteoRobbiati

I think the [tutorials](https://github.com/qiboteam/tutorials) repository could be a nice place where to delve deeper into details of topics (e.g. in the case of the well documented DBI module) in form of notebooks. 

I just opened a PR there: https://github.com/qiboteam/tutorials/pulls. 
If someone else would prefer to take care of this feel, free to do it. Otherwise we can proceed like I suggested.

I would suggest to leave here at least the intro notebook and the readme file for completeness.  

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2024-06-25 09:17 UTC, marekgluza reviewed
@MatteoRobbiati I would leave it to @andrea-pasquale  to decide -  we were aiming to document the module using notebooks.

We could move them for now and then later pull them in but @andrea-pasquale moving them will not break the current docs?

2024-06-26 10:41 UTC, andrea-pasquale requested changes
Thanks @MatteoRobbiati, also the documentation needs to be updated propertly by removing the links to those notebooks.

2024-07-03 05:43 UTC, andrea-pasquale approved these changes

2024-07-03 07:56 UTC, marekgluza approved these changes

2024-07-03 09:11 UTC, merged