Variational Quantum Regression using the Parameter Shift Rule
qiboteam/qibo pull request #654
Opened 2022-10-04 08:04 UTC by MatteoRobbiati

In this example a Variational Quantum Circuit based on the re-uploading strategy is used to tackle a simple 1-dimensional regression problem: (to fit $y= \sin 2x$ ). 

This context is exploited for introducing the Parameter Shift Rule, which is useful for evaluating the gradients of a circuit in a quantum-hardware compatible way. 

A demo markdown is included.

2022-10-04 12:03 UTC, scarrazza reviewed
@MatteoRobbiati thank you very much for this contribution. It is in a really good shape.

I am just wondering if we should place the VQRegressor in a QML / variational module for Qibo and provide the optimizer as a standalone optimizer. @stavros11 what is your opinion about that?

2022-10-10 18:15 UTC, scarrazza commented
@MatteoRobbiati could you please complete this PR by:
- adding this example to the sphinx page: https://github.com/qiboteam/qibo/blob/master/doc/source/code-examples/applications.rst
- including the link to the code: https://github.com/qiboteam/qibo/tree/master/doc/source/code-examples/tutorials

2022-10-11 06:48 UTC, MatteoRobbiati commented
@scarrazza Modifications done, thank you for the comment.

2022-10-11 06:52 UTC, scarrazza commented on doc/source/code-examples/tutorials/vqregressor/REAMDE.md
> +../../../../../examples/vqregressor/README.md
This file has a typo.

2022-10-11 06:53 UTC, scarrazza requested changes
Thank you, but please test sphinx manually every time you perform a change, otherwise you don't really now if things are working well. In fact, at the current state, the tutorial is not appearing in the website due to the typo.

2022-10-11 09:48 UTC, MatteoRobbiati commented
@scarrazza thanks for the advice. I've fixed it and modified the README so that the formulas can be read in documentation.

2022-10-11 11:41 UTC, merged