example quantum anomaly detection
qiboteam/qibo pull request #714
Opened 2022-11-28 13:34 UTC by Simone-Bordoni

To be completed, 
I will add README, tests and .ipynb

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2022-12-05 12:53 UTC, Simone-Bordoni commented
I need some help with tests that are not passing.
When the script is run locally everythong works.

2022-12-05 13:07 UTC, scarrazza commented
From the last crash, seems like you are writing to a folder that does not exist: `results/loss_distribution.png`.

2022-12-12 10:11 UTC, MatteoRobbiati requested changes
Thank you for this, it is in a good shape for me. 
I left in the review some small comments, many of which are really small fixes. I suggest two larger changes:

1. Reverse the location of the "How to run an example" section with the theoretical section in `README.md`. I think it's more natural to read the theoretical background and then have in sequence: explanation of how to execute, anticipation of the results to be derived.
2. Add docstrings in the codes so that the implemented functions are clear when reading.

2022-12-13 12:39 UTC, MatteoRobbiati requested changes
Thank you for your work.

Some more suggestions follow: some more references.
If you like them, you can apply the modifications directly by adding the suggestions I purpose.

2022-12-13 12:39 UTC, MatteoRobbiati commented on examples/anomaly_detection/README.md
> +With this example we want to study the quantum version of a classic machine learning algorithm known as anomaly detection. This algorithm is implemented with an artificial neural network, in particul
```suggestion
With this example we want to study the quantum version of a classic machine learning algorithm known as [anomaly detection](https://arxiv.org/abs/2007.02500). This algorithm is implemented with an artificial neural network, in particular an autoencoder. In quantum machine learning, the autoencoder is realised using a variational quantum circuit. The proposed algorithm is not meant to outperform the classical counterpart on classical data. This work aims to demonstrate that it is possible to use quantum variational algorithms for anomaly detection with possible future advantages in the analysis of quantum data.
```

2022-12-13 12:39 UTC, MatteoRobbiati commented on examples/anomaly_detection/README.md
> +To achieve this it's necessary to train a particular artificial neural network (ANN) architecture called autoencoder. An autoencoder is composed of two main parts: encoder and decoder.
```suggestion
To achieve this it's necessary to train a particular artificial neural network (ANN) architecture called [autoencoder](https://arxiv.org/abs/2003.05991). An autoencoder is composed of two main parts: encoder and decoder.
```

2022-12-13 12:39 UTC, MatteoRobbiati commented on examples/anomaly_detection/README.md
> +```python
```suggestion
```bash
```

2022-12-13 12:39 UTC, MatteoRobbiati commented on examples/anomaly_detection/README.md
> +```python
```suggestion
```bash
```

2022-12-13 12:39 UTC, MatteoRobbiati commented on examples/anomaly_detection/test.py
> +            encoder (qibo.models.Circuit): variational quantum circuit.
```suggestion
            encoder (:class:`qibo.models.circuit.Circuit`): variational quantum circuit.
```

2022-12-13 12:39 UTC, MatteoRobbiati commented on examples/anomaly_detection/test.py
> +            encoder (qibo.models.Circuit): variational quantum circuit (trained).
```suggestion
            encoder (:class:`qibo.models.circuit.Circuit`): variational quantum circuit (trained).
```

2022-12-13 12:39 UTC, MatteoRobbiati commented on examples/anomaly_detection/train.py
> +            encoder (qibo.models.Circuit): variational quantum circuit.
```suggestion
            encoder (:class:`qibo.models.circuit.Circuit`): variational quantum circuit.
```

2022-12-13 12:39 UTC, MatteoRobbiati commented on examples/anomaly_detection/train.py
> +            encoder (qibo.models.Circuit): variational quantum circuit.
```suggestion
            encoder (:class:`qibo.models.circuit.Circuit`): variational quantum circuit.
```

2022-12-13 12:39 UTC, MatteoRobbiati commented on examples/anomaly_detection/train.py
> +            encoder (qibo.models.Circuit): variational quantum circuit.
```suggestion
            encoder (:class:`qibo.models.circuit.Circuit`): variational quantum circuit.
```

2022-12-14 14:38 UTC, MatteoRobbiati commented
I have done a last small fix, now I think it can be merged.

2022-12-14 16:02 UTC, scarrazza approved these changes
Looks good, I have linked the new example in sphinx.

2022-12-14 16:54 UTC, merged