Improvements to `quantum_info` documentation
qiboteam/qibo pull request #992
Opened 2023-08-09 08:37 UTC by renatomello

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

2023-08-09 12:22 UTC, vodovozovaliza requested changes

2023-08-09 12:22 UTC, vodovozovaliza commented on src/qibo/quantum_info/random_ensembles.py
> +        \\rho = \\ketbra{\\psi} \\, ,
```suggestion
        \\rho = \\ketbra{\\psi}{\\psi} \\, ,
```

2023-08-09 12:22 UTC, vodovozovaliza commented on src/qibo/quantum_info/random_ensembles.py
> +        \\rho = \\sum_{k} \\, p_{k} \\, \\ketbra{\\psi_{k}} \\, .
```suggestion
        \\rho = \\sum_{k} \\, p_{k} \\, \\ketbra{\\psi_{k}}{\\psi_{k}} \\, .
```

2023-08-09 12:22 UTC, vodovozovaliza commented on src/qibo/quantum_info/metrics.py
> +    where :math:`I_{d^{2}}` is the :math:`d^{2} \times d^{2}` Identity operator,
```suggestion
    where :math:`I_{d^{2}}` is the :math:`d^{2} \\times d^{2}` Identity operator,
```

2023-08-09 18:48 UTC, vodovozovaliza approved these changes

2023-08-10 07:55 UTC, scarrazza approved these changes

2023-08-10 07:56 UTC, merged