Include `stinespring` representation in `random_quantum_channel`
qiboteam/qibo pull request #996
Opened 2023-08-14 09:14 UTC by renatomello

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [x] Documentation is updated.

2023-08-15 14:49 UTC, AlejandroSopena approved these changes

2023-08-17 11:20 UTC, vodovozovaliza requested changes

2023-08-17 11:20 UTC, vodovozovaliza commented on src/qibo/quantum_info/random_ensembles.py
> +            validate_cp=validate_cp,
```suggestion
            validate_cp=validate_cp,
            nqubits=nqubits,
```

2023-09-22 13:38 UTC, stavros11 approved these changes

2023-09-23 13:11 UTC, merged